apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress-first
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /first
        pathType: Prefix
        backend:
          service:
            name: flask-first
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask-first
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: flask-first
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-first
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-first
  template:
    metadata:
      labels:
        app: flask-first
    spec:
      containers:
      - name: flask-first
        image: toutou98/flask-task1:latest
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
        env:
        - name: MESSAGE
          value: "This is the first service!"